const initialData = [
  {
    name: "Elinor",
    email: "ebuyers0@yolasite.com",
    rating: 3,
    message: "amet consectetuer adipiscing elit proin",
  },
  {
    name: "Fons",
    email: "fsponton1@constantcontact.com",
    rating: 1,
    message: "nec nisi",
  },
  {
    name: "Chery",
    email: "cpetkovic2@fastcompany.com",
    rating: 1,
    message: "quis augue luctus tincidunt",
  },
  {
    name: "Correy",
    email: "cnannoni3@theguardian.com",
    rating: 1,
    message: "lacus at velit",
  },
  {
    name: "Hamid",
    email: "hmingasson4@de.vu",
    rating: 1,
    message: "morbi sem mauris laoreet ut",
  },
  {
    name: "Delmar",
    email: "dfarr5@pagesperso-orange.fr",
    rating: 2,
    message: "nec condimentum",
  },
  {
    name: "Sybilla",
    email: "sivanovic6@sciencedirect.com",
    rating: 5,
    message: "arcu adipiscing",
  },
  {
    name: "Zenia",
    email: "zpremble7@bravesites.com",
    rating: 5,
    message: "cras pellentesque volutpat dui maecenas",
  },
  {
    name: "Stillmann",
    email: "sdewhurst8@wikispaces.com",
    rating: 5,
    message: "venenatis non",
  },
  {
    name: "Mallorie",
    email: "mferrieroi9@msn.com",
    rating: 4,
    message: "lorem ipsum dolor",
  },
  {
    name: "Isacco",
    email: "imuira@jiathis.com",
    rating: 1,
    message: "condimentum id luctus nec molestie",
  },
  {
    name: "Derron",
    email: "dkorneevb@howstuffworks.com",
    rating: 1,
    message: "natoque penatibus et magnis",
  },
  {
    name: "Prudi",
    email: "posanc@w3.org",
    rating: 1,
    message: "tincidunt eu felis fusce",
  },
  {
    name: "Kelsey",
    email: "kwenmand@cam.ac.uk",
    rating: 1,
    message: "urna ut tellus nulla",
  },
  {
    name: "Rhodie",
    email: "rmaffinie@google.com.au",
    rating: 1,
    message: "habitasse platea dictumst",
  },
  {
    name: "Gerianna",
    email: "gcapitanof@virginia.edu",
    rating: 3,
    message: "at nunc commodo",
  },
  {
    name: "Jasper",
    email: "jbottong@friendfeed.com",
    rating: 2,
    message: "vehicula consequat",
  },
  {
    name: "Torre",
    email: "tmarkieh@163.com",
    rating: 2,
    message: "et ultrices posuere cubilia",
  },
  {
    name: "Janey",
    email: "jrykerti@vistaprint.com",
    rating: 3,
    message: "morbi vestibulum velit",
  },
  {
    name: "Whitney",
    email: "wfollitj@xing.com",
    rating: 3,
    message: "sapien arcu sed augue aliquam",
  },
  {
    name: "Allen",
    email: "aroylancek@instagram.com",
    rating: 5,
    message: "luctus rutrum nulla tellus",
  },
  {
    name: "Patricio",
    email: "paronoffl@si.edu",
    rating: 2,
    message: "quam fringilla rhoncus mauris",
  },
  {
    name: "Ann-marie",
    email: "acammockm@umn.edu",
    rating: 5,
    message: "id ornare imperdiet",
  },
  {
    name: "Hollis",
    email: "hbradbornen@mit.edu",
    rating: 5,
    message: "ac diam cras pellentesque volutpat",
  },
  {
    name: "Yulma",
    email: "yboothmano@wikispaces.com",
    rating: 2,
    message: "duis at velit eu est",
  },
];

export default initialData;
